news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.views-field h1'
  elpais:
    url: https://elpais.com
    queries:
       homepage_article_links: '.headline a'
       article_body: '.articulo-cuerpo p'
       article_title: '.articulo-titulares h1'
  colombiacheck:
    url: https://colombiacheck.com
    queries:
      homepage_article_links: '#bloqueImagenes a'
      article_body: '.text-articulos div'
      article_title: '.articulos h2'
  eltiempo:
    url: https://eltiempo.com
    queries:
      homepage_article_links: '.title-container a'
      article_body: '.contenido'
      article_title: '.titulo'