# Generated by Django 2.2.7 on 2019-11-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_id_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firts_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
